version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: firmware_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./deployment/tmp/django_uploads:/tmp/django_uploads
    expose:
      - "8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --worker-class gthread --workers 3 --threads 4 \
             --timeout 30 --keep-alive 30 --max-requests 1000 --max-requests-jitter 200 \ 
             --log-level info \
             --access-logfile - \
             --error-logfile -"

  nginx:
    image: nginx:stable
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/srv/media:ro
      - ./deployment/tmp/nginx_body:/var/lib/nginx/body

  emqx:
    image: emqx/emqx
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    restart: unless-stopped

volumes:
  db_data: