version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: firmware_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./media:/app/media
    expose:
      - "8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 1 --log-level info"

  nginx:
    image: nginx:stable
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/srv/media:ro

  emqx:
    image: emqx/emqx
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    restart: unless-stopped

volumes:
  db_data: