version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: firmware_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build: .
    depends_on:
      - db
      - redis
      - emqx
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./deployment/tmp/django_uploads:/tmp/django_uploads
      - ./deployment/logs/django:/srv/logs/django
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_LOG_DIR=/srv/logs/django
      - LOG_DIR=/srv/logs/django
      - LOG_MAX_BYTES=10485760
      - LOG_BACKUP_COUNT=7
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --worker-class gthread --workers 3 --threads 4 \
             --timeout 30 --keep-alive 30 --max-requests 1000 --max-requests-jitter 200 \ 
             --log-level info \
             --access-logfile - \
             --error-logfile -"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  asgi:
    build: .
    depends_on:
      - db
      - redis
      - emqx
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./deployment/logs/django:/srv/logs/django
    expose:
      - "8001"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_LOG_DIR=/srv/logs/django
      - LOG_DIR=/srv/logs/django
    command: >
      sh -c "uvicorn config.asgi:application --host 0.0.0.0 --port 8001 --loop asyncio"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery_worker:
    build: .
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./deployment/logs/django:/srv/logs/django
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_LOG_DIR=/srv/logs/django
      - LOG_DIR=/srv/logs/django
    command: >
      sh -c "celery -A config.celery_app worker --loglevel=info --concurrency=2"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mqtt_listener:
    build: .
    depends_on:
      - emqx
      - redis
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./deployment/logs/mqtt_listener:/srv/logs/mqtt_listener
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - MQTT_HOST=emqx
      - LOG_DIR=/srv/logs/mqtt_listener
    command: >
      sh -c "python mqtt_listener.py"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:stable
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/srv/media:ro
      - ./deployment/logs/nginx:/var/log/nginx
      - ./deployment/tmp/nginx_body:/var/lib/nginx/body
      - /etc/letsencrypt:/etc/letsencrypt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  emqx:
    image: emqx/emqx
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    restart: unless-stopped

volumes:
  db_data:
  redis_data: