# Generated by Django 5.2.6 on 2025-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('mac_address', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
